"""002_add_username_account

Revision ID: 1846f948e23b
Revises: b6ea1a476e07
Create Date: 2025-12-03 08:32:54.296597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1846f948e23b'
down_revision: Union[str, None] = 'b6ea1a476e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('username', sa.VARCHAR(length=50), server_default='User_847a10a4-2c18-4b4c-aae2-f938fc9ecac8', nullable=False))
    op.create_unique_constraint(None, 'account', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'username')
    # ### end Alembic commands ###
