"""003_create_exercise

Revision ID: 7f86f13de1c7
Revises: 1846f948e23b
Create Date: 2025-12-08 19:58:40.284877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f86f13de1c7'
down_revision: Union[str, None] = '1846f948e23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('category', sa.Enum('CARDIO', 'STRENGTH', 'STRETCH', name='exercisecategory'), nullable=True),
    sa.Column('muscle_group', sa.Enum('BACK', 'CHEST', 'ARMS', 'LEGS', 'SHOULDERS', name='exercisemusclegroups'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('update_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Date of last updated'),
    sa.CheckConstraint('length(description) >= 5', name='description_exercise_min_length'),
    sa.CheckConstraint('length(name) >= 3', name='name_exercise_min_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise')
    # ### end Alembic commands ###
