"""004_create_table_workout_and_workout_exercise

Revision ID: 981318f363ec
Revises: 7f86f13de1c7
Create Date: 2025-12-09 17:48:47.925164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981318f363ec'
down_revision: Union[str, None] = '7f86f13de1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=15), nullable=False),
    sa.Column('note', sa.VARCHAR(length=100), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', name='workoutenum'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('update_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Date of last updated'),
    sa.CheckConstraint('length(title) >= 3', name='title_workout_min_length'),
    sa.CheckConstraint('note IS NULL OR length(note) >= 5', name='note_workout_min_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('workout_exercise',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('sets', sa.SmallInteger(), nullable=True),
    sa.Column('reps', sa.SmallInteger(), nullable=True),
    sa.Column('weight', sa.SmallInteger(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Date of created'),
    sa.Column('update_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Date of last updated'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_exercise_exercise_id'), 'workout_exercise', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_exercise_workout_id'), 'workout_exercise', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercise_workout_id'), table_name='workout_exercise')
    op.drop_index(op.f('ix_workout_exercise_exercise_id'), table_name='workout_exercise')
    op.drop_table('workout_exercise')
    op.drop_table('workout')
    # ### end Alembic commands ###
